# Generated by Django 6.0.7 on 2026-07-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="nom_candidat",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
