# Generated by Django 6.0.7 on 2026-07-28 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0002_alter_cv_nom_candidat"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="offre",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidats",
                to="matching.offre",
            ),
            preserve_default=False,
        ),
    ]
