# Generated by Django 6.0.7 on 2026-07-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0003_cv_offre"),
    ]

    operations = [
        migrations.AddField(
            model_name="offre",
            name="date_modification",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
