# Generated by Django 6.0.7 on 2026-07-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0004_offre_date_modification"),
    ]

    operations = [
        migrations.AddField(
            model_name="offre",
            name="statut",
            field=models.CharField(
                choices=[
                    ("ouverte", "Ouverte"),
                    ("fermee", "Fermée"),
                    ("pourvue", "Pourvue"),
                ],
                default="ouverte",
                max_length=10,
            ),
        ),
    ]
