# Generated by Django 6.0.7 on 2026-08-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0005_offre_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="email",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="cv",
            name="telephone",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
