# Generated by Django 6.0.7 on 2026-08-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0006_cv_email_cv_telephone"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="competences_communes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="score",
            name="competences_manquantes",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
