# Generated by Django 6.0.7 on 2026-08-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0007_score_competences_communes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="adresse",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="cv",
            name="behance",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="cv",
            name="github",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="cv",
            name="gitlab",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="cv",
            name="linkedin",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="cv",
            name="portfolio",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
