# Generated by Django 6.0.7 on 2026-08-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0008_cv_adresse_cv_behance_cv_github_cv_gitlab_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="sous_scores",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
