# Generated by Django 6.0.7 on 2026-08-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0009_score_sous_scores"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
