# Generated by Django 6.0.7 on 2026-08-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0010_cv_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="offre",
            name="avantages",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="offre",
            name="description_complete",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="offre",
            name="missions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="offre",
            name="profil",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="offre",
            name="salaire",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="offre",
            name="type_contrat",
            field=models.CharField(
                choices=[
                    ("CDI", "CDI"),
                    ("CDD", "CDD"),
                    ("Stage", "Stage"),
                    ("Freelance", "Freelance"),
                    ("Intérim", "Intérim"),
                ],
                default="CDI",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="offre",
            name="statut",
            field=models.CharField(
                choices=[("ouverte", "Ouverte"), ("fermee", "Fermée")],
                default="ouverte",
                max_length=10,
            ),
        ),
    ]
