# Generated by Django 6.0.7 on 2026-08-28 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0011_offre_avantages_offre_description_complete_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offre",
            name="avantages",
        ),
        migrations.RemoveField(
            model_name="offre",
            name="description_complete",
        ),
        migrations.RemoveField(
            model_name="offre",
            name="missions",
        ),
        migrations.RemoveField(
            model_name="offre",
            name="profil",
        ),
    ]
